name: Build and Run Docker for TeX to PDF and PNG Conversion

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ amin ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t resume .
      - name: Run the Docker container
        run: docker run --rm -v ${{ github.workspace }}:/workspace resume
      - name: Remove Docker image
        run: docker rmi resume
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "this.is.aditeya@gmail.com"
          git config --global user.name "GH Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "latest update" && git push)